# Generated by Django 3.1.3 on 2020-12-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='data_produkcji',
            new_name='data',
        ),
    ]
