# Generated by Django 3.1.3 on 2020-12-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0003_auto_20201217_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='data_premiery',
            new_name='dataPremiery',
        ),
    ]
