# Generated by Django 3.1.3 on 2020-12-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0005_auto_20201217_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='plakat',
            field=models.ImageField(default=None, upload_to='plakaty'),
        ),
    ]
